# Generated by Django 3.1b1 on 2020-07-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedvideos',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
